# 分析基盤などでゲームを識別するためのコード。英数字5桁。
title_cd: "FF001"

# ゲームのタイトル名
application_name: "app_seed_example1"

# ゲームを運営する際のタイムゾーン
timezone: "Tokyo"

# ゲームを運営する際の業務日付の更新時刻
start_time_of_day: "04:00"

# ログインURL
login_url: "/api/1.0.0/actions.html"

# ログイン後の署名の検証に使用されるOAuthのコンシューマシークレット
consumer_secret: "cpqomf5gs4ob6prd5w5zd52yg9du7150"

# ログインの際に呼び出されるフック名
login_hook_stored_script_name: "RubyStoredScript.provide_login_bonus"

# 商品購入の際に呼び出されるフック名
# purchase_stored_script_name: "RubyStoredScript.buy"

# 商品購入後に呼び出されるフック名
purchase_log_stored_script_name: "RubyStoredScript.purchase_log"

# 各種プラットフォーム情報
platform:
  title: "サンプルアプリ１"
  target: "sandbox"
